import Link from "next/link";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Front-End Insights",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={poppins.className}>
        <div className="flex min-h-screen flex-col items-center justify-between max-w-5xl mx-auto p-3 antialiased">
          <header className="flex items-center justify-between w-full py-10">
            <span className="text-2xl font-black cursor-default">INSIGHTS</span>
            <nav className="flex gap-10 max-[600px]:gap-3 ">
              <Link
                href="/"
                className="hover:underline decoration-sky-700 decoration-2"
              >
                Início
              </Link>
              <Link
                href="/about"
                className="hover:underline decoration-sky-700 decoration-2"
              >
                Sobre
              </Link>
              <Link
                href="/admin/subscribers"
                className="hover:underline decoration-sky-700 decoration-2 max-[600px]:mr-1"
              >
                Inscritos
              </Link>
            </nav>
          </header>

          {children}

          <footer className="p-10">
            <p>Feito com Next.js 13.4</p>
          </footer>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
